# opyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build handwired horne'
on: 
  push:
    branches:
      - master
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["horne_left","horne_right"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=n\nCONFIG_ZMK_POINTING=y"]'
      alphas: '["qwerty"]'
      nav: '["vi"]'
      clipboard: '["mac"]'
      layers: '["default"]'
      branches: '["zmkfirmware/zmk/main"]'
