# opyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build handwired horne'
on: 
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["xiao_ble//zmk"]'
      shield: '["horne_left rgbled_adapter","horne_right rgbled_adapter"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=n\nCONFIG_ZMK_POINTING=y\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000"]'
      alphas: '["qwerty"]'
      nav: '["vi"]'
      clipboard: '["mac"]'
      layers: '["default"]'
      modules: '["caksoylar/zmk-rgbled-widget/main"]'
      branches: '["zmkfirmware/zmk/main"]'
